name: UnicomTask

on:
  push:
    branches: main
  gollum:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Unzip latest release
        run: |
          wget https://github.com/srcrs/UnicomTask/releases/latest/download/unicom-task_scf.zip
          unzip unicom-task_scf.zip

      - name: Edit
        run: |
          rm -R -- */
          mkdir tmp
          find . -type f -exec sed -i.bak "s/..\/..\/tmp\/log.txt/.\/tmp\/log.txt/g" {} \;

      - name: Build and publish
        env:
          USERS_COVER: ${{ secrets.USERS_COVER }}
        run: |
          echo "$USERS_COVER"|base64 -d > ./config.json
          python main.py
