name: UnicomTask

on:
  push:
    branches: main
  gollum:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set proxy
        env:
          config: ${{ secrets.config }}
        run: |
          sudo apt-get install shadowsocks-libev simple-obfs proxychains-ng
          sudo -E sh -c 'echo $config|base64 -d > /etc/shadowsocks-libev/config.json'
          sudo sh -c 'echo "\
          [Unit]
          Description=Shadowsocks
          After=network.target
          [Service]
          ExecStart=ss-local -c /etc/shadowsocks-libev/config.json
          Rnestart=on-abort
          [Install]
          WantedBy=multi-user.target\
          ">/etc/systemd/system/shadowsocks.service'
          sudo systemctl daemon-reload
          sudo systemctl start shadowsocks
          sleep 3s
          systemctl status --no-pager shadowsocks
          sudo sed -i 's/socks4 	127.0.0.1 9050/socks5 127.0.0.1 1080/g' /etc/proxychains4.conf
          sudo sed -i 's/#quiet_mode/quiet_mode/g' /etc/proxychains4.conf

      - name: Setup pytools
        run: |
          curl -O https://raw.githubusercontent.com/w311ang/pytools/main/pytools.py
          curl -O https://raw.githubusercontent.com/w311ang/pytools/main/aes.py

      - name: Build and publish
        env:
          USERS_COVER: ${{ secrets.USERS_COVER }}
          jmail: ${{ secrets.jmail }}
        run: |
          echo "$USERS_COVER"|base64 -d > ./config.json
          proxychains python index.py
